import Loader from "./components/Loader/Loader.jsx";
import AuthLayout from "./components/AuthLayout.jsx"
import Login from "./components/Login/Login.jsx"
import Home from "./components/Home/Home.jsx"
import Header from "./components/Header/Header.jsx"
import Post from "./components/Post/Post.jsx"
import User from "./components/User/User.jsx";
import CommentCard from "./components/CommentCard/CommentCard.jsx";
import Account from "./components/Account/Account.jsx";
import NewPost from "./components/NewPost/NewPost.jsx"
import Register from "./components/Register/Register.jsx"
import UpdateProfile from "./components/UpdateProfile/UpdateProfile.jsx"
import UpdatePassword from "./components/UpdatePassword/UpdatePassword.jsx";
import ForgotPassword from "./components/ForgotPassword/ForgotPassword.jsx";
import ResetPassword from "./components/ResetPassword/ResetPassword.jsx";
import UserProfile from "./components/UserProfile/UserProfile.jsx";
import Search from "./components/Search/Search.jsx";
import NotFound from "./components/NotFound/NotFound.jsx";
export {Loader,AuthLayout,Login,Home,Header,Post,User,CommentCard,Account,NewPost,Register,UpdateProfile,UpdatePassword,ForgotPassword,ResetPassword,UserProfile,Search,NotFound}